# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

install:
- R CMD build --no-build-vignettes .
- R CMD check --no-vignettes *tar.gz

after_success:
- Rscript -e 'covr::codecov()'
