dist: trusty
sudo: required
language: R
cache: packages

r_github_packages:
- hadley/devtools
- johndharrison/wdman

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

env:
  matrix:
  - NOT_CRAN=true
R:
- release

after_success:
- Rscript -e 'covr::codecov()'
