# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get install build-essential chrpath libssl-dev libxft-dev
  - sudo apt-get install libfreetype6 libfreetype6-dev
  - sudo apt-get install libfontconfig1 libfontconfig1-dev
  - export PHANTOM_JS="phantomjs-2.1.1-linux-i686"
  - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
  - sudo tar xvjf $PHANTOM_JS.tar.bz2
  - sudo mv $PHANTOM_JS /usr/local/share
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
  - Rscript -e 'devtools::install_deps(dependencies = TRUE)'

install:
  - R CMD build --no-build-vignettes .
  - R CMD check --no-vignettes *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'
