dist: trusty
sudo: required
language: R
cache: packages

warnings_are_errors: FALSE

r_packages:
  - devtools
  - wdman
  - rvest
  - selectr
  - tibble
  - tm
  - tidytext
  - wordcloud

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

env:
  matrix:
  - NOT_CRAN=true

R:
- release

after_success:
- Rscript -e 'covr::codecov()'
