---
title: "Introdução ao valor"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introducao ao valor}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# valorrr

## Instalar o pacote

```{r, eval = FALSE}
# install.packages('devtools')
devtools::install_github('tomasbarcellos/valorrr')
```

## Uso do pacote

```{r, eval = FALSE}
library(valorrr)
email <- 'meu-email@provedor'
senha <- 'minha_senha'
sessao_logada <- login(email, senha)
# dar uma olhada do objeto da sessao
sessao_logada
```

```{r, echo = FALSE, eval = FALSE}
library(valorrr)
config <- readLines('../.valor')
email <- config[1]
senha <- config[2]
sessao_logada <- login(email, senha)
# dar uma olhada do objeto da sessao
sessao_logada
```

## Lendo noticias

```{r, eval = FALSE}
links_noticias <- sessao_logada %>% links_pagina()

noticias <- sessao_logada %>% ler_noticia(links_noticias)
```

A resposta da função `ler_noticia` é um objeto de classe `noticia`.

```{r, eval = FALSE}
noticias[[1]]
```

# Pequeno exemplo de uso

## Pegando dados

```{r, eval = FALSE}
library(magrittr)
library(purrr)

resposta <- sessao_logada %>% procurar_valor(termo = 'eleicoes')

links_eleicoes <- attr(resposta, 'links')

noticias_eleicoes <- map(links_eleicoes, safely(ler_noticia),
                         sessao = sessao_logada) %>% map('result') %>% 
  extract(!sapply(., is.null)) %>% 
  map_df(~ .x)
```

## Visualizando informações

```{r, eval = FALSE}
noticias_eleicoes$tags %>% unlist() %>% table() %>%
  sort(decreasing = TRUE) %>% magrittr::extract(. > 1)
```

```{r, eval = FALSE}
library(dplyr)
library(tidytext)
library(tm)

# Texto é uma lista, precisa ser vetor para tidytext
noticias_df <- noticias_eleicoes %>% mutate(texto = paste(unlist(texto), collapse = " "))

tidy_noticias <- noticias_df %>% select(titulo, texto) %>% 
  unnest_tokens(palavra, texto)

stop_pt <- tibble(palavra = c(stopwords('pt-br'), 'sobre'))

noticias_limpo <- tidy_noticias %>% anti_join(stop_pt)

# 10 Palavras mais comuns
noticias_limpo %>% 
  count(palavra, sort = TRUE)

# Nuvem de palavras
library(wordcloud)
minha_nuvem <- function(palavras, freq) {
  wordcloud(palavras, freq, max.words = 100,
                      random.color = TRUE, colors = c('orange', 'darkblue', 'lightgray'))
}
```


```{r, fig.height=7, fig.width=10, eval = FALSE}
noticias_limpo %>% 
  count(palavra, sort = TRUE) %>% 
  with(minha_nuvem(palavra, n))
```

